name: fishspot_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: ^8.3.0
  http: ^1.3.0
  http_parser: ^4.1.2
  mime: ^2.0.0
  image_picker: ^1.1.2
  shared_preferences: ^2.5.2
  provider: ^6.1.2
  flutter_svg_provider: ^1.0.7
  flutter_svg: ^2.0.17
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  flutter_dotenv: ^5.2.1
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  geolocator: ^13.0.4
  intl: ^0.20.2
  uuid: ^4.5.1
  path: ^1.9.0
  url_launcher: ^6.3.1
  flutter_native_splash: ^2.4.4
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/fish-spot-icon.png"
  android: true
  ios: true
  web: false

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/fish-spot-icon.png"
  min_sdk_android: 21
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: true
    image_path: "assets/fish-spot-icon.png"
